### ISSUE TITLE
Default generator is unable to determine client IP address

### ISSUE THREAD

**Issue by justin13888** [rayriffy/elysia-rate-limit#17] opened 2024-03-27 05:17 UTC
![image](https://github.com/rayriffy/elysia-rate-limit/assets/20733699/fe852f84-d316-4aaf-a9c6-7e7cd4497e98)

**Describe the bug**
Default generator is unable to determine client IP address.

**To Reproduce**
I used the example code in README

```
import { Elysia } from 'elysia'
import { rateLimit } from 'elysia-rate-limit'

const app = new Elysia().use(rateLimit({
        max: 1,
        duration: 60,
        responseMessage: "Too many login attempts. Please try again later.",
    }))
    .post(...)
    .listen(3000)
```

**Expected behavior**
It should just work

**Additional context**
*Versions*
Bun: 1.0.33
elysia-rate-limit: 3.0.0

Let me know if other details would help!

**Comment by rayriffy** [comment] 2024-03-27 21:06
Hey! I am unable to reproduce this issue on Bun 1.0.35, could you try to update your Bun runtime first? Maybe you should check your environment first that you can call [`server.requestIp()`](https://github.com/oven-sh/bun/pull/6165), and has a value.

If you found that using Bun API to determine IP address is unreliable, then you can implement your own way to distinct your user with rate limit with `generator` option.

Closing this issue for now.

**Closed by rayriffy** 2024-03-27 21:06 UTC
