### ISSUE TITLE
Unable to determine client IP address

### ISSUE THREAD

**Issue by Mikey-ShenSu** [rayriffy/elysia-rate-limit#22] opened 2024-04-01 21:06 UTC
**Before open the issue**
- [x] I tried remove `node_modules/`, `bun.lockb`, and do a clean installation.
- [x] I tried update Bun, and Elysia to latest version.

**Describe the bug**
```[elysia-rate-limit] generator is unable to determine client IP address. Are you using older version of Bun?```

**To Reproduce**
I imported and called .use(), nothing else.
![Screenshot 2024-04-02 at 05 05 16](https://github.com/rayriffy/elysia-rate-limit/assets/153639584/8b13c1ff-9710-41a0-b5ea-82603a4d38ab)

**Expected behavior**
This error message should not appear, and plugin can successfully detect the IP address.

**Environments**
1. Bun version: 1.1.0
2. Host Operating system: macOS 14.4.1 
3. Running on Docker?: no

**Screenshots**
![Screenshot 2024-04-02 at 05 03 39](https://github.com/rayriffy/elysia-rate-limit/assets/153639584/13a51d10-f3ab-49ee-8dc5-4a7a05971edf)

**Additional context**
package.json:
```
{
  "name": "study-app",
  "version": "1.0.2",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "bun run --watch src/index.ts",
    "start": "NODE_ENV=production bun run src/index.ts"
  },
  "dependencies": {
    "@elysiajs/bearer": "^1.0.2",
    "@elysiajs/cors": "^1.0.2",
    "@elysiajs/jwt": "^1.0.2",
    "@elysiajs/static": "^1.0.2",
    "@elysiajs/swagger": "^0.8.5",
    "@types/pluralize": "^0.0.33",
    "elysia": "^1.0.10",
    "elysia-rate-limit": "^3.1.0",
    "ioredis": "^5.3.2",
    "mongoose": "^8.2.1",
    "openai": "^4.31.0",
    "pluralize": "^8.0.0",
    "tencentcloud-sdk-nodejs-sms": "^4.0.789",
    "uuid": "^9.0.1"
  },
  "devDependencies": {
    "@types/uuid": "^9.0.8",
    "bun-types": "latest"
  },
  "module": "src/index.js"
}
```

**Comment by rayriffy** [comment] 2024-04-01 22:11
I am also running in same macOS, and Bun version as yours but as I tried on my example project `.requestIp()` still works perfectly. This error will appear if `.requestIp()` returns `null` which can causes from following 2 conditions, neither fits.

![CleanShot 2024-04-02 at 07 09 20](https://github.com/rayriffy/elysia-rate-limit/assets/22584594/154ae9b6-70e0-4e51-9b00-450edef02263)

Can you make a small reproduction project and attach repository to this issue? I am a bit worried now, because by default I want to just support native Bun API without any overhead headers check. If I implement proxy header checks it wouldn't going to solve this issue either.

But anyways, related to https://github.com/rayriffy/elysia-rate-limit/issues/17 and maybe https://github.com/elysiajs/elysia/issues/377 https://github.com/oven-sh/bun/issues/6613.

**Comment by Mikey-ShenSu** [comment] 2024-04-01 22:42
> I am also running in same macOS, and Bun version as yours but as I tried on my example project `.requestIp()` still works perfectly. This error will appear if `.requestIp()` returns `null` which can causes from following 2 conditions, neither fits.
> 
> ![CleanShot 2024-04-02 at 07 09 20](https://private-user-images.githubusercontent.com/22584594/318580493-154ae9b6-70e0-4e51-9b00-450edef02263.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMTA5NDIsIm5iZiI6MTcxMjAxMDY0MiwicGF0aCI6Ii8yMjU4NDU5NC8zMTg1ODA0OTMtMTU0YWU5YjYtNzBlMC00ZTUxLTliMDAtNDUwZWRlZjAyMjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDIyMzA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyN2FjM2E5MjFhMWM1ZDUzYmVkZDJiMDY0YzdiZGE3MTU2NTc3MTY2NDI3MDY5YzBmYWVkYTI0ZDI4OTQ2ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f2yYasr4w5pWH1YB1CpTYwvpFZf8vDE9aHrE4BRklJQ)
> 
> Can you make a small reproduction project and attach repository to this issue? I am a bit worried now, because by default I want to just support native Bun API without any overhead headers check. If I implement proxy header checks it wouldn't going to solve this issue either.
> 
> But anyways, related to #17 and maybe [elysiajs/elysia#377](https://github.com/elysiajs/elysia/issues/377) [oven-sh/bun#6613](https://github.com/oven-sh/bun/issues/6613).

Unfortunately, I am unable to re-produce the project as It contains sensitive codes. But I have implemented `server.requestIp()` as below:

```typescript
  .use(
    rateLimit({
      responseMessage: {
        code: "Too Many Requests",
        message: "You have exceeded the 10 requests in 1 minute limit!",
        status: 429,
      },
    })
  )
  .onRequest(({ request }) => {
    console.log(app.server!.requestIP(request)?.address);
  })
```

What I have discovered is `server.requestIp()` currently is returning the real IP address of visitors but still prints out the error log as show in the **server** log

Local:
```bash
mikey@Mikeys-MBP api % bun dev
$ bun run --watch src/index.ts
🦊 Study APP is running at http://localhost:3002
::1
[elysia-rate-limit] generator is unable to determine client IP address. Are you using older version of Bun?
```

Server:
```log
/root/.pm2/logs/ddxx-api-out.log last 15 lines:
0|ddxx-api | 🦊 Study APP is running at http://localhost:3002
0|ddxx-api | ::ffff:49.86.208.**
0|ddxx-api | ::ffff:49.86.208.**
0|ddxx-api | ::ffff:49.86.208.**
0|ddxx-api | ::ffff:49.86.208.**
0|ddxx-api | ::ffff:49.86.208.**
0|ddxx-api | [elysia-rate-limit] generator is unable to determine client IP address. Are you using older version of Bun?
```

**Comment by rayriffy** [comment] 2024-04-03 19:19
I've updated packaged to version `3.1.2`. It won't fix this issue though but I hope that it might hint some thing for me, and unfortunately because you cannot create a separate small project as a reproduction I am going to asked you to install this version and get me some logs. It possible that there might be behavior difference in hooks because you're trying `server.requestIp()` in `onRequest` hook but plugin is running on `onBeforeHandle` hook.

Also more than just a warning message, maybe you could also add more `console.log` lines within `node_modules` as well. So I can get more detail on what's going on. 🙏🏻

![CleanShot 2024-04-04 at 04 15 10](https://github.com/rayriffy/elysia-rate-limit/assets/22584594/ba08daad-6d74-43db-b265-f01cbcf88647)

**Comment by Mikey-ShenSu** [comment] 2024-04-03 19:52
> I've updated packaged to version `3.1.2`. It won't fix this issue though but I hope that it might hint some thing for me, and unfortunately because you cannot create a separate small project as a reproduction I am going to asked you to install this version and get me some logs. It possible that there might be behavior difference in hooks because you're trying `server.requestIp()` in `onRequest` hook but plugin is running on `onBeforeHandle` hook.
> 
> Also more than just a warning message, maybe you could also add more `console.log` lines within `node_modules` as well. So I can get more detail on what's going on. 🙏🏻
> 
> ![CleanShot 2024-04-04 at 04 15 10](https://private-user-images.githubusercontent.com/22584594/319322297-ba08daad-6d74-43db-b265-f01cbcf88647.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzM4MjEsIm5iZiI6MTcxMjE3MzUyMSwicGF0aCI6Ii8yMjU4NDU5NC8zMTkzMjIyOTctYmEwOGRhYWQtNmQ3NC00M2RiLWIyNjUtZjAxY2JjZjg4NjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE5NDUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNGZhZTNlYmVlZDczNjJiNjg0OGE5YWY0MTVlNDlmZWI4ZTBhYjcwZTI2NjcwNzZlNTIxODMwYTQyNmY4YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jnRDOnoZbMrfzDMHaWn_xtJfy-vMcCJRPlj4SgvX6g4)

There is no longer error message prining, and 

![image](https://github.com/rayriffy/elysia-rate-limit/assets/153639584/f5ae5521-1d85-43ff-a874-a1237aea41b3)

Local:
```
undefined
::1
::1
::1
::1
::1
::1
```

Server:
```
0|ddxx-api | undefined

0|ddxx-api  | ::ffff:49.86.208.**
0|ddxx-api  | ::ffff:49.86.208.**
```


I also added following in the `defaultKeyGenerator.js`:
```
console.log(request)
console.log(server.requestIP(request))
```

Below, is what I have found, if I comment out connectToMongoDb and connectToRedis, and no request related to such, it will not return `undefined` at all.
![image](https://github.com/rayriffy/elysia-rate-limit/assets/153639584/06545fdc-a999-438c-8bab-2c40206bd724)

**Comment by rayriffy** [comment] 2024-04-03 20:11
When you added back both `connectToMongoDB()` and `connectToRedis()` then `request` inside plugin become undefined and warning starts logging again, right?

**Comment by Mikey-ShenSu** [comment] 2024-04-03 20:13
> When you added back both `connectToMongoDB()` and `connectToRedis()` then `request` inside plugin become undefined and warning starts logging again, right?

Nope. It will just print "undefined" for the first request, and all the following requests will be printing the IP address as it should be.

**Closed** 2024-04-03 20:21 UTC
Labels: needs repro, type: bug

**Comment by DaniumX** [comment] 2024-08-06 06:59
> I have just removed `node_modules` and `bun.lockb`, and reinstalled again with
> 
> ```json
>  "elysia-rate-limit": "^3.1.3"
> ```
> 
> I can confirm that in both local and server environment that this issue is gone for me.

Not for me. I also noticed that this error only arises when making requests from Eden/browser, not when using a REST client such as Hoppscotch.
